[[puzzles]]
name = "3005. Count Elements With Maximum Frequency"
links = ["https://leetcode.com/contest/weekly-contest-380/problems/count-elements-with-maximum-frequency/"]
[[puzzles.examples]]
args = [[1,2,2,3,1,4]]
result = 4
[[puzzles.examples]]
args = [[1,2,3,4,5]]
result = 5

[[puzzles]]
name = "3010. Divide an Array Into Subarrays With Minimum Cost I"
links = ["https://leetcode.com/contest/biweekly-contest-122/problems/divide-an-array-into-subarrays-with-minimum-cost-i/"]
[[puzzles.examples]]
args = [[1,2,3,12]]
result = 6
[[puzzles.examples]]
args = [[5,4,3]]
result = 12
[[puzzles.examples]]
args = [[10,3,1,1]]
result = 12

[[puzzles]]
name = "3028. Ant on the Boundary"
links = ["https://leetcode.com/contest/weekly-contest-383/problems/ant-on-the-boundary/"]
[[puzzles.examples]]
args = [[2,3,-5]]
result = 1
[[puzzles.examples]]
args = [[3,2,-3,-4]]
result = 0

[[puzzles]]
name = "3038. Maximum Number of Operations With the Same Score I"
links = ["https://leetcode.com/contest/biweekly-contest-124/problems/maximum-number-of-operations-with-the-same-score-i/"]
[[puzzles.examples]]
args = [[3,2,1,4,5]]
result = 2
[[puzzles.examples]]
args = [[3,2,6,1,4]]
result = 1

[[puzzles]]
name = "PWC 250 - Task 1: Smallest Index"
links = ["https://theweeklychallenge.org/blog/perl-weekly-challenge-250/"]
[[puzzles.examples]]
args = [[0, 1, 2]]
result = 0
[[puzzles.examples]]
args = [[4, 3, 2, 1]]
result = 2

[[puzzles]]
name = "1380. Lucky Numbers in a Matrix"
links = ["https://leetcode.com/problems/lucky-numbers-in-a-matrix/description/", "https://theweeklychallenge.org/blog/perl-weekly-challenge-251/"]
ignore = true
[[puzzles.examples]]
args = [[[3,7,8],[9,11,13],[15,16,17]]]
result = [15]
[[puzzles.examples]]
args = [[[1,10,4,2],[9,3,8,7],[15,16,17,12]]]
result = [12]
[[puzzles.examples]]
args = [[[7,8],[1,2]]]
result = [7]

[[puzzles]]
name = "2778. Sum of Squares of Special Elements "
links = ["https://leetcode.com/problems/sum-of-squares-of-special-elements/description/", "https://theweeklychallenge.org/blog/perl-weekly-challenge-251/"]
ignore = true
[[puzzles.examples]]
args = [[1,2,3,4]]
result = 21
[[puzzles.examples]]
args = [[2,7,1,19,18,3]]
result = 63

[[puzzles]]
name = "1365. How Many Numbers Are Smaller Than the Current Number"
links = ["https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/description/", "https://theweeklychallenge.org/blog/perl-weekly-challenge-257/"]
[[puzzles.examples]]
args = [[8,1,2,2,3]]
result = [4,0,1,1,3]
[[puzzles.examples]]
args = [[6,5,4,8]]
result = [2,1,0,3]
[[puzzles.examples]]
args = [[7,7,7,7]]
result = [0,0,0,0]

[[puzzles]]
name = "1295. Find Numbers with Even Number of Digits"
links = ["https://leetcode.com/problems/find-numbers-with-even-number-of-digits/"]
[[puzzles.examples]]
args = [[12,345,2,6,7896]]
result = 2
[[puzzles.examples]]
args = [[555,901,482,1771]]
result = 1
