[[puzzles]]
name = "3005. Count Elements With Maximum Frequency"
links = ["https://leetcode.com/contest/weekly-contest-380/problems/count-elements-with-maximum-frequency/"]
[[puzzles.examples]]
args = [[1,2,2,3,1,4]]
result = 4
[[puzzles.examples]]
args = [[1,2,3,4,5]]
result = 5

[[puzzles]]
name = "3010. Divide an Array Into Subarrays With Minimum Cost I"
links = ["https://leetcode.com/contest/biweekly-contest-122/problems/divide-an-array-into-subarrays-with-minimum-cost-i/"]
[[puzzles.examples]]
args = [[1,2,3,12]]
result = 6
[[puzzles.examples]]
args = [[5,4,3]]
result = 12
[[puzzles.examples]]
args = [[10,3,1,1]]
result = 12

[[puzzles]]
name = "3028. Ant on the Boundary"
links = ["https://leetcode.com/contest/weekly-contest-383/problems/ant-on-the-boundary/"]
[[puzzles.examples]]
args = [[2,3,-5]]
result = 1
[[puzzles.examples]]
args = [[3,2,-3,-4]]
result = 0

[[puzzles]]
name = "3038. Maximum Number of Operations With the Same Score I"
links = ["https://leetcode.com/contest/biweekly-contest-124/problems/maximum-number-of-operations-with-the-same-score-i/"]
[[puzzles.examples]]
args = [[3,2,1,4,5]]
result = 2
[[puzzles.examples]]
args = [[3,2,6,1,4]]
result = 1
